### PR TITLE
Add support for MAC OS X

### PR DESCRIPTION
**Pull request by vrasneur**
Hi,

Here is a pull request that adds MAC OS X support for arbtt.

The MAC OS X support uses only the Haskell FFI: there are no additional C/Objective-C files nor a separate library.

I have made some tests and it seems to work fine:
- the build is OK (you just need to install pkgconfig and pcre with MacPorts or homebrew).
- I have extracted the Graphics/OSX/Window.hs file into a separate program and valgrind did not find memory leaks.
- diacritics are handled correctly in the window titles

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks. This looks sensible, but I have no idea about OSX. And obviously, I cannot test it...

The file `src/Graphics/OSX/Window.hs` looks rather large? Did you write this file completely yourself, or did you copy it from somewhere?

**Comment by vrasneur** [comment]
Yes, It's 100% my code.

I have tried to find a Haskell library that binds the "low-level" Apple C code (CoreFoundation, IOKit, Carbon, ...). But I have only found GUI bindings for the higher level Objective-C libraries (mainly Cocoa and AppKit).

But anyway, as the "low-level" libraries are C code, it seems more simple to use the Haskell FFI and to "import" all the functions I needed to make arbtt work.

Maybe someone on the mailing list has a Mac?

**Comment by nomeata** [comment]
> Yes, It's 100% my code.

Perfect. Maybe add a copyright header and leave your name and address there, for future reference?

> Maybe someone on the mailing list has a Mac?

Sure, give it a shot! But I’m happy to merge your changes even if it’s just you who tested the changes.

**Comment by vrasneur** [comment]
Okay,

I will add a copyright header, GPL2 is OK for you?
And I will post some detailed compilation and installation steps to the mailing list.

But I cannot start until end of next week (too many other things to do ;-).

**Comment by nomeata** [comment]
Sounds good, and no hurry.

**Comment by miheerdew** [comment]
I have a Mac. I can test it.

**Comment by vrasneur** [comment]
I have added the copyright header.
And I have rebased my branch: it is easier to read only a single commit instead of 7 small commits.

Hi @miheerdew. Thanks for your help in testing this arbtt branch.
I will post the compilation instructions to the arbtt mailing list.

**Comment by vrasneur** [comment]
Here is the post on the mailing list that explains how to test: https://lists.nomeata.de/archive/arbtt/2016/000367.html

**Comment by miheerdew** [comment]
I am able to successfully build and run it.

**Comment by nomeata** [comment]
Great! Next step: Add OS X to the documentation, in particular the installation section. The webpage is `arbtt.html` in the repository, and the documentation is buitl from `doc/arbtt.xml`.

**Comment by vrasneur** [comment]
I don't think you will provide Mac binaries, as you don't have a Mac.

So, only the "source installation" part must be updated in the documentation.
I don't see this "source installation" part in `doc/arbtt.xml`. I should only modify the `arbtt.html` file?

**Comment by vrasneur** [comment]
I have updated the documentation for Mac OS X.
Can you review it?

**Comment by nomeata** [comment]
Looks good, thanks!

**Pull request closed without merging**
